### ISSUE TITLE
Write and wait for response

### ISSUE THREAD

**Issue by psd24** [capacitor-community/bluetooth-le#103]
**Is your feature request related to a problem? Please describe.**
How can I write and wait for a response?

**Comment by pwespi** [comment]
By using `write` instead of `writeWithoutResponse`, there will be an acknowledgement on the Bluetooth layer (see e.g. the Android documentation [here](https://developer.android.com/reference/android/bluetooth/BluetoothGattCharacteristic#WRITE_TYPE_DEFAULT)). If you need to get an actual value back, you have to use `read` or `startNotifications` in combination with `write` or `writeWithoutResponse`, but that depends on the device and communication protocol that is used.
