### ISSUE TITLE
BleClient initializiation - is it really needed and why?

### ISSUE THREAD

**Issue by karunt** [capacitor-community/bluetooth-le#313]
When using this plug-in in an angular app, I chose to put all my Ble related (example, requestDevice, connect, disconnect, etc.) in a separate service (BleService), which can then be made available to all the components in my app.  Currently, I initialize BleClient in the constructor of BleService.  When a component using BleService is created for the first time, BleClient gets initialized.  Now if I comment out BleService.initialize() from the code and recompile my app, I would expect BleClient to have been destroyed (because of recompiling my code) and BleClient won't get initialized again (since that part of the code has been commented out) when the component using BleService is created again.  What's odd is that I can still use all the features of this plug-in without an initialized BleClient.  So my question is - what purpose does BleClient serve when using this plug in?  Why do we need to initialize and use it when many of the functions in this plug-in seem to work without it?

**Comment by pwespi** [comment]
On Android and iOS, the `initialize` call checks for permissions and requests them if necessary. It also initializes some things on the native side. So it is required, and without it the other calls won't work.

On web, the `initialize` call checks if the Web Bluetooth API is available in the current browser. So it's still useful but not strictly required.

If you're developing on a real Android or iOS device with live reloading, it could be that the native side is still initialized when you uncomment the initialize call (because it has been called before). But leaving it uncommented will break a production build.
