### ISSUE TITLE
Bonding

### ISSUE THREAD

**Issue by pwespi** [capacitor-community/bluetooth-le#50]
Feature request mentioned in #5.

This will be Android only:
* [createBond](https://developer.android.com/reference/android/bluetooth/BluetoothDevice#createBond()) 
* [getBondState](https://developer.android.com/reference/android/bluetooth/BluetoothDevice.html#getBondState())
* there is no public API for removeBond on BluetoothDevice

On iOS there is no API to handle bonding. It is performed automatically when accessing a characteristic that requires security. See e.g. https://devzone.nordicsemi.com/f/nordic-q-a/8507/getting-an-ios-central-app-to-bond

Web:
* Chrome on macOS: automatically performs bonding when accessing a secure characteristic (as on iOS)
* Chrome on Windows: does not perform bonding
* Chrome on Android: does not perform bonding

**Comment by pwespi** [comment]
`createBond` and `isBonded`have been added for Android.

**Comment by crebuh** [comment]
How do you handle the situation when the user wants to remove the device connection completely? 

Currently I have the issue that when the user disconnects from the device it is still bonded. In this case I will have to guide him to the system settings and remove the bond from there, otherwise the device and my app will always reconnect automatically.
