### ISSUE TITLE
BLE disconnect doesn’t throw error when device ID doesn’t pertain to a connected peripheral

### ISSUE THREAD

**Issue by karunt** [capacitor-community/bluetooth-le#594]
**Describe the bug**
When using the disconnect function with a device ID to which the android device isn’t connected, disconnect still resolves and no error is thrown.

**To Reproduce**
Call BLEClient.disconnect with a device ID to which android device isn’t connected. Disconnect will resolve as opposed to throwing an error.

**Expected behavior**
Disconnect should throw an error instead.

**Screenshots**

**Plugin version:**
- @capacitor-community/bluetooth-le: latest version

**Desktop (please complete the following information):**
- OS:
- Browser: Firefox, IE
- Version

**Smartphone (please complete the following information):**
- Device: Android
- OS:
- Browser: Firefox, IE

**Additional context**

**Comment by pwespi** [comment]
That's by design and it's the same behavior on all platforms. You can say that when you call `disconnect`, the desired state is to be disconnected, and if you're already disconnected, then it's all good. It's the same with the `connect` call. If you're already connected, and you call `connect` again, it doesn't throw an error. Is there a problem with that?
